name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y git zip unzip openjdk-11-jdk libffi-dev libncurses5-dev python3-pip

    - name: Install Buildozer
      run: |
        pip install --upgrade pip
        pip install cython virtualenv
        pip install buildozer

    - name: Install Android SDK
      run: |
        sudo mkdir -p /home/runner/android-sdk/cmdline-tools
        wget https://dl.google.com/android/repository/commandlinetools-linux-9123335_latest.zip
        unzip -q commandlinetools-linux-9123335_latest.zip -d /home/runner/android-sdk/cmdline-tools
        mv /home/runner/android-sdk/cmdline-tools/cmdline-tools /home/runner/android-sdk/cmdline-tools/tools

        yes | /home/runner/android-sdk/cmdline-tools/tools/bin/sdkmanager --sdk_root=/home/runner/android-sdk --licenses
        yes | /home/runner/android-sdk/cmdline-tools/tools/bin/sdkmanager --sdk_root=/home/runner/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2"

        echo "ANDROID_HOME=/home/runner/android-sdk" >> $GITHUB_ENV
        echo "ANDROID_SDK_ROOT=/home/runner/android-sdk" >> $GITHUB_ENV
        echo "/home/runner/android-sdk/platform-tools" >> $GITHUB_PATH
        echo "/home/runner/android-sdk/build-tools/33.0.2" >> $GITHUB_PATH

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Slingo-APK
        path: bin/*.apk
