name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-11-jdk python3-pip libffi-dev libssl-dev \
            git build-essential pkg-config zlib1g-dev libncurses5-dev libtinfo5 \
            libgl1-mesa-dev libgles2-mesa liblzma-dev

      - name: Install Buildozer
        run: |
          pip install --upgrade pip
          pip install buildozer cython virtualenv

      - name: Install Android SDK and NDK
        run: |
          sudo mkdir -p /opt/android-sdk
          sudo mkdir -p /opt/android-ndk
          sudo chown -R $USER:$USER /opt/android-sdk /opt/android-ndk

          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdtools.zip
          unzip cmdtools.zip -d /opt/android-sdk/cmdline-tools
          mv /opt/android-sdk/cmdline-tools/cmdline-tools /opt/android-sdk/cmdline-tools/tools

          yes | /opt/android-sdk/cmdline-tools/tools/bin/sdkmanager --sdk_root=/opt/android-sdk --licenses
          yes | /opt/android-sdk/cmdline-tools/tools/bin/sdkmanager --sdk_root=/opt/android-sdk \
            "platform-tools" "platforms;android-31" "build-tools;33.0.2" "ndk;23.1.7779620"

      - name: Build APK
        env:
          ANDROIDSDK: /opt/android-sdk
          ANDROIDNDK: /opt/android-sdk/ndk/23.1.7779620
          PATH: /opt/android-sdk/platform-tools:/opt/android-sdk/build-tools/33.0.2:$PATH
        run: |
          buildozer init | true
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: slingo-apk
          path: bin/*.apk
