name: Build Android APK (Docker)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Show Docker info
        run: |
          docker --version
          docker info

      - name: Build APK inside the official buildozer image
        env:
          BUILDOZER_WARN_ON_ROOT: "0"
        run: |
          # Clean old artifacts
          rm -rf .buildozer bin || true
          # Run build in container; mount the repo into /home/user/app
          docker run --rm \
            -e BUILDOZER_WARN_ON_ROOT=0 \
            -v "$PWD":/home/user/app \
            -w /home/user/app \
            kivy/buildozer:stable \
            bash -lc "apt-get update && apt-get install -y git zip unzip && buildozer -v android debug"

      # Always grab logs so we can diagnose anything quickly
      - name: Upload build logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: buildozer-logs
          path: |
            .buildozer/buildozer.log
            .buildozer/android/**/*.log
            .buildozer/android/**/*.txt

      - name: Upload APK
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: slingo-apk
          path: bin/*.apk
